/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplyRecordCard: typeof import('./src/components/profile/ApplyRecordCard.vue')['default']
    BottomFooter: typeof import('./src/components/BottomFooter.vue')['default']
    EducationCard: typeof import('./src/components/resume/EducationCard.vue')['default']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    JobCard: typeof import('./src/components/resume/JobCard.vue')['default']
    JobExperience: typeof import('./src/components/JobExperience.vue')['default']
    JobExperienceCard: typeof import('./src/components/resume/JobExperienceCard.vue')['default']
    LanguageCard: typeof import('./src/components/resume/LanguageCard.vue')['default']
    ProjectCard: typeof import('./src/components/resume/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagButton: typeof import('./src/components/TagButton.vue')['default']
    TopHeader: typeof import('./src/components/TopHeader.vue')['default']
    WorkExperience: typeof import('./src/components/WorkExperience.vue')['default']
  }
}
