/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomFooter: typeof import('./src/components/BottomFooter.vue')['default']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    JobExperience: typeof import('./src/components/JobExperience.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagButton: typeof import('./src/components/TagButton.vue')['default']
    TopHeader: typeof import('./src/components/TopHeader.vue')['default']
    WorkExperience: typeof import('./src/components/WorkExperience.vue')['default']
  }
}
